server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/danlinblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    com.danlinhou.blog: DEBUG
#    org.mybatis: ERROR
